language: ruby

sudo: false

cache: bundler

rvm:
 - 1.9.3
 - 2.0.0
 - 2.1
 - 2.2

env:
  - DATABASE_URL=mysql2://localhost/tracks_test
  - DATABASE_URL=sqlite3:db/test.sqlite3

bundler_args: --without development --jobs=3 --retry=3

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/site.yml.tmpl config/site.yml"

script: "bin/rake ci"

notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tracks"
    skip_join: true
