--- 
javascripts: 
- tracks: 
  - prototype
  - effects
  - dragdrop
  - controls
  - application
  - calendar
  - calendar-en
  - calendar-setup
  - accesskey-hints
  - todo-items
  - niftycube
  - protoload
  - flashobject
  - lowpro
stylesheets: 
- tracks: 
  - standard
  - calendar-system
  - niftyCorners